export const exportOffersMapper = {
  idOffer: "id",
  fileNumber: "sale.vehicle.fileNumber",
  supplyType: "sale.supplyType",
  offerType: "offerType",
  amount: "amount",
  auctionStartPrice: "sale.auctionStartPrice",
  immediatePurchasePrice: "sale.immediatePurchasePrice",
  make: "sale.vehicle.brandLabel",
  model: "sale.vehicle.modelLabel",
  version: "sale.vehicle.versionLabel",
  mileage: "sale.vehicle.mileage",
  expectedEntryStockDate: "sale.vehicle.entryStockDate",
  timeOfTheOffer: "createdAt",
  pointOfSale: "sale.vehicle.pointofsale.name",
};
